# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uTQgUIc9WWLzbDDJu3NksyN0tRk2Ipe
"""

!pip install streamlit
!pip install scikit-surprise

# Downgrade numpy to a version compatible with scikit-surprise
# and reinstall scikit-surprise to ensure compatibility.
# You will likely need to restart the runtime after running this cell.
!pip uninstall numpy scikit-surprise -y # Ensure a clean slate
!pip install "numpy<2.0" # Install the desired numpy version first
!pip install scikit-surprise --no-deps # Install scikit-surprise, avoiding new dependency resolution for numpy

import streamlit as st
import pickle
import pandas as pd

# Load trained SVD model
with open("svd_model.pkl", "rb") as f:
    model = pickle.load(f)

# Load data (books & ratings)
books_df = pd.read_csv("Books.csv")      # book_id, title
ratings_df = pd.read_csv("Ratings.csv", encoding='latin1')  # user_id, book_id, rating

st.set_page_config(page_title="Book Recommendation System")

st.title(" Book Recommendation System")
st.write("SVD-based Personalized Book Recommendations")

# User input
user_id = st.number_input("Enter User ID", min_value=1, step=1)

def recommend_books(user_id, n=5):
    book_ids = books_df['book_id'].unique()
    predictions = []

    for book_id in book_ids:
        pred = model.predict(user_id, book_id)
        predictions.append((book_id, pred.est))

    predictions.sort(key=lambda x: x[1], reverse=True)
    top_books = predictions[:n]

    result = []
    for book_id, rating in top_books:
        title = books_df[books_df['book_id'] == book_id]['title'].values[0]
        result.append((title, round(rating, 2)))

    return result

if st.button("Recommend Books"):
    recommendations = recommend_books(user_id)

    st.subheader("Top 5 Recommended Books:")
    for i, (title, rating) in enumerate(recommendations, 1):
        st.write(f"{i}. **{title}** —  {rating}")